In [3]:
import pandas as pd
df = pd.read_csv("pajak.csv")
df

    ID                                            PAJAK  PENDAPATAN  TAHUN
0    1                   PAJAK KENDARAAN BERMOTOR (PKB)    44031390   2013
1    2    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)    50000571   2013
2    3  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)     1112290   2013
3    4     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)    46100060   2013
4    5                        PAJAK AIR PERMUKAAN (PAP)     5915131   2013
5    6                                      PAJAK ROKOK     1340340   2013
6    7                   PAJAK KENDARAAN BERMOTOR (PKB)    49388400   2014
7    8    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)     5182390   2014
8    9  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)     1186300   2014
9   10     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     5300000   2014
10  11                        PAJAK AIR PERMUKAAN (PAP)     1340300   2014
11  12                                      PAJAK ROKOK    13403000   2014
12  13                   PAJAK KENDARAAN BERMOTOR (PKB)     2377000   2015
13  14    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)    45523000   2015
14  15  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)     1106800   2015
15  16     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     5248607   2015
16  17                        PAJAK AIR PERMUKAAN (PAP)     5240000   2015
17  18                                      PAJAK ROKOK    16868000   2015
18  19                   PAJAK KENDARAAN BERMOTOR (PKB)    52040000   2016
19  20    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)     8782070   2016
20  21  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)      779000   2016
21  22     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     8422650   2016
22  23                        PAJAK AIR PERMUKAAN (PAP)     2303000   2016
23  24                                      PAJAK ROKOK     7830000   2016
24  25                   PAJAK KENDARAAN BERMOTOR (PKB)     5340500   2017
25  26    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)     7130000   2017
26  27  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)     1400000   2017
27  28     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     2314030   2017
28  29                        PAJAK AIR PERMUKAAN (PAP)     9247000   2017
29  30                                      PAJAK ROKOK     8321000   2017
30  31                   PAJAK KENDARAAN BERMOTOR (PKB)      770000   2018
31  32    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)      573000   2018
32  33  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)      560000   2018
33  34     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     2910000   2018
34  35                        PAJAK AIR PERMUKAAN (PAP)      909000   2018
35  36                                      PAJAK ROKOK     1909000   2018
36  37                   PAJAK KENDARAAN BERMOTOR (PKB)      430000   2019
37  38    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)     5470000   2019
38  39  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)    16030000   2019
39  40     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     7947000   2019
40  41                        PAJAK AIR PERMUKAAN (PAP)     4700000   2019
41  42                                      PAJAK ROKOK      759000   2019
42  43                   PAJAK KENDARAAN BERMOTOR (PKB)     5878100   2020
43  44    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)     9587800   2020
44  45  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)     9587800   2020
45  46     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     4680000   2020
46  47                        PAJAK AIR PERMUKAAN (PAP)     9987000   2020
47  48                                      PAJAK ROKOK     8951000   2020
48  49                   PAJAK KENDARAAN BERMOTOR (PKB)      970000   2021
49  50    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)      571100   2021
50  51  BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)     5600000   2021
51  52     PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)      410000   2021
52  53                        PAJAK AIR PERMUKAAN (PAP)      903000   2021
53  54                                      PAJAK ROKOK     3301000   2021

In [4]:
df.head() # Returns the first 5 rows for quickly checking data
df.shape  # Returns a dimensionality of the DataFrame
df.describe().T # Generates descriptive statistic
df.isnull().values.any() # Returns any value is missing in DataFrame
df.isnull().sum() #  Returns how many missing values exist in the DataFrame

ID            0
PAJAK         0
PENDAPATAN    0
TAHUN         0
dtype: int64

In [5]:
# Number of unique <SOURCE>
df["TAHUN"].nunique() # Count number of distinct SOURCE elements
df["TAHUN"].value_counts()# Returns counts of SOURCE rows 
df["PAJAK"].value_counts() # Returns counts of COUNTRY rows

PAJAK KENDARAAN BERMOTOR (PKB)                     9
BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)      9
BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)    9
PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)       9
PAJAK AIR PERMUKAAN (PAP)                          9
PAJAK ROKOK                                        9
Name: PAJAK, dtype: int64

In [6]:
df.groupby("PAJAK")["PENDAPATAN"].agg({"mean"})
df.groupby(["PAJAK", 'TAHUN'])["PENDAPATAN"].mean()

PAJAK                                            TAHUN
BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)    2013     50000571.0
                                                 2014      5182390.0
                                                 2015     45523000.0
                                                 2016      8782070.0
                                                 2017      7130000.0
                                                 2018       573000.0
                                                 2019      5470000.0
                                                 2020      9587800.0
                                                 2021       571100.0
BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II)  2013      1112290.0
                                                 2014      1186300.0
                                                 2015      1106800.0
                                                 2016       779000.0
                                                 2017      1400000.0
                                                 2018       560000.0
                                                 2019     16030000.0
                                                 2020      9587800.0
                                                 2021      5600000.0
PAJAK AIR PERMUKAAN (PAP)                        2013      5915131.0
                                                 2014      1340300.0
                                                 2015      5240000.0
                                                 2016      2303000.0
                                                 2017      9247000.0
                                                 2018       909000.0
                                                 2019      4700000.0
                                                 2020      9987000.0
                                                 2021       903000.0
PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)     2013     46100060.0
                                                 2014      5300000.0
                                                 2015      5248607.0
                                                 2016      8422650.0
                                                 2017      2314030.0
                                                 2018      2910000.0
                                                 2019      7947000.0
                                                 2020      4680000.0
                                                 2021       410000.0
PAJAK KENDARAAN BERMOTOR (PKB)                   2013     44031390.0
                                                 2014     49388400.0
                                                 2015      2377000.0
                                                 2016     52040000.0
                                                 2017      5340500.0
                                                 2018       770000.0
                                                 2019       430000.0
                                                 2020      5878100.0
                                                 2021       970000.0
PAJAK ROKOK                                      2013      1340340.0
                                                 2014     13403000.0
                                                 2015     16868000.0
                                                 2016      7830000.0
                                                 2017      8321000.0
                                                 2018      1909000.0
                                                 2019       759000.0
                                                 2020      8951000.0
                                                 2021      3301000.0
Name: PENDAPATAN, dtype: float64

In [7]:
agg_df = df.groupby(["PAJAK", 'TAHUN'])["PENDAPATAN"].mean().sort_values(ascending=False)
agg_df.head()

PAJAK                                          TAHUN
PAJAK KENDARAAN BERMOTOR (PKB)                 2016     52040000.0
BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)  2013     50000571.0
PAJAK KENDARAAN BERMOTOR (PKB)                 2014     49388400.0
PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)   2013     46100060.0
BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)  2015     45523000.0
Name: PENDAPATAN, dtype: float64

In [8]:
agg_df = agg_df.reset_index()
agg_df.head()

                                           PAJAK  TAHUN  PENDAPATAN
0                 PAJAK KENDARAAN BERMOTOR (PKB)   2016  52040000.0
1  BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)   2013  50000571.0
2                 PAJAK KENDARAAN BERMOTOR (PKB)   2014  49388400.0
3   PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)   2013  46100060.0
4  BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)   2015  45523000.0

In [10]:
# Convert AGE variable to categorical variable and adding it to agg_df

my_labels = ['2013_2014', '2015_2016', '2017_2018', '2019_2020','2021']
agg_df["YEAR_CUT"] = pd.cut(x=agg_df["TAHUN"], bins=[2013, 2014, 2015, 2018, 2019, 2021], labels=my_labels)
agg_df.tail(10) # Just checking data

,PAJAK,TAHUN,PENDAPATAN,YEAR_CUT
44,PAJAK AIR PERMUKAAN (PAP),2018,909000.0,2017_2018
45,PAJAK AIR PERMUKAAN (PAP),2021,903000.0,2021
46,BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II),2016,779000.0,2017_2018
47,PAJAK KENDARAAN BERMOTOR (PKB),2018,770000.0,2017_2018
48,PAJAK ROKOK,2019,759000.0,2019_2020
49,BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I),2018,573000.0,2017_2018
50,BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I),2021,571100.0,2021
51,BEA BALIK NAMA KENDARAAN BERMOTOR II (BBNKB II),2018,560000.0,2017_2018
52,PAJAK KENDARAAN BERMOTOR (PKB),2019,430000.0,2019_2020
53,PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB),2021,410000.0,2021

In [11]:
# Identify new level-based customers
agg_df["customers_level_based"] = [f"{i[0]}_{i[1]}_{i[2]}_{i[-1]}" for i in agg_df.values]

In [12]:
agg_df = agg_df.loc[:, ["customers_level_based", "PENDAPATAN"]].groupby("customers_level_based").agg({"PENDAPATAN": "mean"}).sort_values(by="PENDAPATAN", ascending=False).reset_index()
agg_df["customers_level_based"].head() # Just checking data again

0    PAJAK KENDARAAN BERMOTOR (PKB)_2016_52040000.0...
1    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)_...
2    PAJAK KENDARAAN BERMOTOR (PKB)_2014_49388400.0...
3    PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)_2...
4    BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)_...
Name: customers_level_based, dtype: object

In [13]:
agg_df["SEGMENT"] = pd.qcut(agg_df["PENDAPATAN"], 4, labels=["D", "C", "B", "A"])
agg_df.head()

                               customers_level_based  PENDAPATAN SEGMENT
0  PAJAK KENDARAAN BERMOTOR (PKB)_2016_52040000.0...  52040000.0       A
1  BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)_...  50000571.0       A
2  PAJAK KENDARAAN BERMOTOR (PKB)_2014_49388400.0...  49388400.0       A
3  PAJAK BAHAN BAKAR KENDARAAN BERMOTOR (PBBKB)_2...  46100060.0       A
4  BEA BALIK NAMA KENDARAAN BERMOTOR I (BBNKB I)_...  45523000.0       A

In [14]:
# Describe the segments and especially "C"

agg_df.groupby(["SEGMENT"]).agg({"PENDAPATAN": ["mean", "max", "sum"]})

agg_df[agg_df["SEGMENT"] == "C"].describe()

         PENDAPATAN
count  1.300000e+01
mean   2.999774e+06
std    1.477480e+06
min    1.340300e+06
25%    1.909000e+06
50%    2.377000e+06
75%    4.680000e+06
max    5.240000e+06

In [20]:
new_user = "PAJAK ROKOK_2019_759000"
print(agg_df[agg_df["customers_level_based"] == new_user])

Empty DataFrame
Columns: [customers_level_based, PENDAPATAN, SEGMENT]
Index: []